### PR TITLE
176 add statement to speaker page

### PR DESCRIPTION
**Pull request by vguen**
Resolve https://github.com/CaptainFact/captain-fact/issues/176

Frontend of https://github.com/CaptainFact/captain-fact-api/pull/310

### CODE REVIEW

**Comment by Miragide** [comment]
@vguen @Betree what can we do here?

**Review by Betree — COMMENTED** [review]
@vguen There was a great work started on this :raised_hands: It still needs some iterations to be ready to ship. Can I help with anything in this regard? If you don't have the bandwidth now and prefer to pass the issue to someone else that's absolutely fine.

**Comment by Miragide** [comment]
@vguen souhaites tu poursuivre ?

**Comment by vguen** [comment]
@Miragide je souhaite continuer ce développement 🙂

**Comment by Betree** [comment]
@vguen we need to move forward with this one, the elections are coming soon, and the recent discussions have surfaced this issue as a priority. There are many conflicts on this PR, so I'll start something fresh, taking as much as I can from this PR (it was a great start!).

**Pull request closed without merging**
