### PR TITLE
66 background sound

### PR DESCRIPTION
**Pull request by Vayel**
https://github.com/CaptainFact/captain-fact/issues/66

As @Betree said in the issue, determining whether a statement is confirmed or not is highly political. I just summed all the upvotes to the comments (positive if the comment is confirming, negative otherwise). When this sum is higher than `CONFIRMED_STATEMENT_MIN_VOTES`, the statement is considered confirmed.

- [x] The different sounds probably need to be changed. 
- [x] I don't think the function `isStatementConfirmed()` is in the right file

### CODE REVIEW

**Comment by Betree** [comment]
Having a `isStatementConfirmed` is a good idea. It could go in a new `app/lib/comments_utils.js` (you can use a better namespace if you think of one).

Why not in a selector: for now we only need to run this calculation when there is a background sound to play. If we add it in a selector (to call it from `select`) it will run every time we add/remove a comment or when the statement is edited.

**Comment by Vayel** [comment]
@Betree Should it be `app/lib/comments_utils.js` because it manipulates comments or `app/lib/statements_utils.js` instead, as it concerns statements?

**Comment by Vayel** [comment]
Here are a couple of sounds for refuted statements (I guess the sounds for confirmed and neutral are alright):

https://notificationsounds.com/message-tones/no-manners-50

https://notificationsounds.com/message-tones/get-outta-here-505

https://notificationsounds.com/message-tones/may-i-have-your-attention-424

https://notificationsounds.com/wake-up-tones/happy-taxi-horn-245

https://notificationsounds.com/wake-up-tones/robot-cant-believe-his-eyes-237

https://notificationsounds.com/message-tones/finger-pushed-193

https://notificationsounds.com/message-tones/quiet-twitch-111

https://notificationsounds.com/message-tones/credulous-512

Any preference @Betree ?

**Comment by Betree** [comment]
@Vayel Up to you,

**Comment by Betree** [comment]
Miss click, sorry :)

> @Betree Should it be `app/lib/comments_utils.js` because it manipulates comments or `app/lib/statements_utils.js` instead, as it concerns statements?

No personal preference here, both seems valid to me

Regarding the sounds https://notificationsounds.com/message-tones/quiet-twitch-111 is my favorite, I find the other ones too aggressive.

**Comment by Vayel** [comment]
@Betree I chose `statements_utils` because it's more natural to look for such a file when we ask the question `is there a function to check whether a statement is confirmed?`.

**Comment by Betree** [comment]
One issue that I see is that the sound can be too low/high in comparison with the video. We should fetch the volume from the video and adapt accordingly. But that out-of-scope here :)

Thanks @Vayel, great contribution as always!

**Pull request merged**
