### PR TITLE
Adds opengraph information to the speaker page.

### PR DESCRIPTION
**Pull request by steelstyle**
Added basic opengraph information for the speaker page too.

### CODE REVIEW

**Review by Betree — APPROVED** [review]
Looking good!

**Comment by Betree** [comment]
Test with deploy preview + https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeploy-preview-681--captainfact.netlify.app%2Fs%2F6712: 

image

**Comment by steelstyle** [comment]
We can later think about including a picture. However I doubt that existing picture have good enough quality.

**Comment by Betree** [comment]
@steelstyle yep the existing pic is very low-res, like 50x50

**Pull request merged**
